// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSRj0VU5jyQyTEjez1MI680yZ7YY75R2s',
    appId: '1:233148717436:android:9d623877b2fcd0677aecf9',
    messagingSenderId: '233148717436',
    projectId: 'ecollect-25b4c',
    storageBucket: 'ecollect-25b4c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8z8UaLGCRB64JgS20vKj9MNc0rkO8yk',
    appId: '1:233148717436:ios:f9eee47aee7c7bad7aecf9',
    messagingSenderId: '233148717436',
    projectId: 'ecollect-25b4c',
    storageBucket: 'ecollect-25b4c.firebasestorage.app',
    iosBundleId: 'com.collection.qr',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWWBlfPXvbver5Pqy7NY3lUh1OnLz_cQ',
    appId: '1:233148717436:web:3f7e9fd09fe6ea047aecf9',
    messagingSenderId: '233148717436',
    projectId: 'ecollect-25b4c',
    authDomain: 'ecollect-25b4c.firebaseapp.com',
    storageBucket: 'ecollect-25b4c.firebasestorage.app',
    measurementId: 'G-8VLRLCM63P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi8z8UaLGCRB64JgS20vKj9MNc0rkO8yk',
    appId: '1:233148717436:ios:f59a7d1d0e9111727aecf9',
    messagingSenderId: '233148717436',
    projectId: 'ecollect-25b4c',
    storageBucket: 'ecollect-25b4c.firebasestorage.app',
    iosBundleId: 'com.example.collectionQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWWBlfPXvbver5Pqy7NY3lUh1OnLz_cQ',
    appId: '1:233148717436:web:705bf739ea25ac187aecf9',
    messagingSenderId: '233148717436',
    projectId: 'ecollect-25b4c',
    authDomain: 'ecollect-25b4c.firebaseapp.com',
    storageBucket: 'ecollect-25b4c.firebasestorage.app',
    measurementId: 'G-3EJ1J30L5Q',
  );
}
